services:
  app:
    platform: linux/amd64
    build:
      context: .
    ports:
      - '8000:80'
    environment:
      # Required
      SOURCE_TRAEFIK_API_BASE_URL: http://example.com/api
      SOURCE_TRAEFIK_ENDPOINT_URL: https://192.168.1.100:443
      PROXY_TRAEFIK_SERVICE_NAME: forwarding-upstream
      PROXY_TRAEFIK_SERVICE_ENDPOINTS: example-endpoint,second-example-endpoint
      # Optional
      SOURCE_TRAEFIK_ENDPOINTS_FILTER: example-upstream-endpoint-to-filter-by
      PORT: 80 # Default is 80